### ISSUE TITLE
Fatal error: Uncaught exception 'Trello\Exception\RuntimeException' 

### ISSUE THREAD

**Issue by ygerzen** [cdaguerre/php-trello-api#38]
hi
i catch fatal error, what is this?

Fatal error: Uncaught exception 'Trello\Exception\RuntimeException' with message 'T' in /www/lib/Trello/HttpClient/Listener/ErrorListener.php:62 Stack trace: #0 [internal function]: Trello\HttpClient\Listener\ErrorListener->onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /www/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /www/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event)) #3 /www/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(589): Symfony\C in /www/lib/Trello/HttpClient/HttpClient.php on line 152

code in my project:

ini_set('error_reporting', E_ALL);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
require 'vendor/autoload.php';
use Trello\Client;
use Trello\Manager;

$client = new Client();

$client->authenticate('example-dsfsfdsf34f43f34ff3f', ''example-dffdsfde3r4443ffvf33', Client::AUTH_URL_CLIENT_ID);

$manager = new Manager($client);

$card = $manager->getCard(''example-fe4f4f54f45f');
echo $client;

**Comment by goatherd** [comment]
https://github.com/cdaguerre/php-trello-api/blob/master/lib/Trello/HttpClient/HttpClient.php#L148 does wrap a client exception from the guzzle library.

As `'T'` is not a very detailed error message and the detail of the event queue not visible in the dump I can only assume you have a dependency issue (no ext-curl) or something blocking the network.

This is not really a problem with the trello api as far as I can see.

**Comment by augustohp** [comment]
Error messages responses appear to be different than the ones being treated, at least that we could change in order to provide relevant error messages.
